name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./vendor/bundle
            ./node_modules
          key: ${{ runner.os }}-deploy-${{ hashFiles('Gemfile.lock', 'yarn.lock') }}
      - name: AWS SSM to .env
        uses: deptno/action-aws-ssm-to-dotenv@v1.3.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        with:
          ssm-path: /ds_gifs_api/production/env
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Bootstrap
        run: |
          ./bin/bootstrap
      - name: Deploy
        run: |
          ./bin/deploy

